Config = { }

Config.Language = {
    ["NotHoldingAnimal"] = "You Got Nothing To Sell",
    ["NotInTheButcher"] = "I won't buy that animal",
    ["AnimalSold"] = "Thanks for the deal!",
    notabutcher = "You Dont Have The Right Job",
}

Config.ItemQuantity = {
    ["Max"] = 2,
    ["Min"] = 1
}

Config.aiButcherped = true -- spawn ai butched ped set to false if you dont want an ai butcher ped to spawn 
Config.joblocked = false -- lock the butcher so only people with the job can access. u can change access to each butcher by editing this  ["butcherjob"] = "butcher"
Config.maxpelts = 8-- max pelts allowed on back of horse


Config.Butchers = {
    {["butchername"] = "Valentine Butcher", ["butcherjob"] = "butcher",    ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(-339.0141, 767.6358, 115.5645),    ["heading"] = 100.41544342041,   ["radius"] = 3.0},
    {["butchername"] = "Strawberry Butcher", ["butcherjob"] = "butcher",   ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(-1753.143, -392.4201, 155.2578),   ["heading"] = 181.37438964844,   ["radius"] = 3.0},
    {["butchername"] = "Blackwater Butcher", ["butcherjob"] = "butcher",  ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(-754.0, -1285.158, 42.83),    ["heading"] = 273.579,   ["radius"] = 3.0},
    {["butchername"] = "Annesburg Butcher", ["butcherjob"] = "butcher",    ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(2934.51, 1301.159, 43.48365),      ["heading"] = 70.572128295898,   ["radius"] = 3.0},
    {["butchername"] = "Van Horn Butcher",  ["butcherjob"] = "butcher",    ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(2991.844, 572.0218, 43.36182),     ["heading"] = 259.52850341797,   ["radius"] = 3.0},
    {["butchername"] = "Rhodes Butcher",   ["butcherjob"] = "butcher",     ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(1297.578, -1277.589, 74.88102),    ["heading"] = 146.60472106934,   ["radius"] = 3.0},
    {["butchername"] = "Armadillo Butcher", ["butcherjob"] = "butcher",    ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(-3691.438, -2623.152, -14.75121),  ["heading"] = 0.46632757782936,  ["radius"] = 3.0},
    {["butchername"] = "Tumbleweed Butcher", ["butcherjob"] = "butcher",   ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(-5510.371, -2947.005, -1.894515),  ["heading"] = 251.54911804199,   ["radius"] = 3.0}
}



-- to add more rewards on each animal edit the givenItem table. for example change ["givenItem"] ={ "meat"}, to ["givenItem"] ={ "meat","Feather"},
Config.Animals = {
    -- Animals
   -- [-1124266369]  = {["name"] = "Bear",                      ["givenItem"] ={},      ["money"] = 1.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 957520252,    ["good"] = 143941906,    ["perfect"] = 1292673537 },
    [-15687816381] = {["name"] = "Big Horn Ram",              ["givenItem"] ={},      ["money"] = 0.12,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 1796037447,   ["good"] = -476045512,   ["perfect"] = 1795984405 },
    [2028722809]   = {["name"] = "Boar",                      ["givenItem"] ={},      ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 1248540072,   ["good"] = nil,          ["perfect"] = -1858513856 },
    [-1963605336]  = {["name"] = "Buck",                      ["givenItem"] ={ },      ["money"] = 1,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 1603936352,   ["good"] = -868657362,   ["perfect"] = -702790226 },
   -- [-2004866590]  = {["name"] = "Aligator",                  ["givenItem"] ={ },      ["money"] = 1,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = -1243878166,   ["good"] = nil,   ["perfect"] = -1475338121 },
    [1556473961]   = {["name"] = "Bison",                     ["givenItem"] ={ },      ["money"] = 2,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = -1730060063,  ["good"] = -591117838,   ["perfect"] = -237756948 },
    [1957001316]   = {["name"] = "Bull",                      ["givenItem"] ={ },      ["money"] = 0.12,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 9293261,      ["good"] = -336086818,   ["perfect"] = -53270317 },
    [1110710183]   = {["name"] = "Deer",                      ["givenItem"] ={ },      ["money"] = 0.75,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = -662178186,   ["good"] = -1827027577,  ["perfect"] = -1035515486 },
    [-1003616053]  = {["name"] = "Duck",                      ["givenItem"] ={ },  ["money"] = 0.37,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1459778951]   = {["name"] = "Eagle",                     ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [831859211]    = {["name"] = "Egret",                     ["givenItem"] ={ },  ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
   -- [-2021043433]  = {["name"] = "Elk",                       ["givenItem"] ={ },      ["money"] = 1.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 2053771712,   ["good"] = 1181652728,   ["perfect"] = -1332163079 },
    [252669332]    = {["name"] = "American Red Fox",          ["givenItem"] ={ },      ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 1647012424,   ["good"] = 238733925,    ["perfect"] = 500722008 },
    [-1143398950]  = {["name"] = "Big Grey Wolf",             ["givenItem"] ={ },      ["money"] = 0.62,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 85441452,     ["good"] = 1145777975,   ["perfect"] = 653400939 },
    [-885451903]   = {["name"] = "Medium Grey Wolf",          ["givenItem"] ={ },      ["money"] = 0.62,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 85441452,     ["good"] = 1145777975,   ["perfect"] = 653400939 },
    [-829273561]   = {["name"] = "Small Grey Wolf",           ["givenItem"] ={ },      ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 85441452,     ["good"] = 1145777975,   ["perfect"] = 653400939 },
    [1104697660]   = {["name"] = "Vulture",                   ["givenItem"] ={ },  ["money"] = 0.12,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-407730502]   = {["name"] = "Snapping Turtle",           ["givenItem"] ={ },      ["money"] = 0.05,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-466054788]   = {["name"] = "Wild Turkey",               ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-2011226991]  = {["name"] = "Wild Turkey",               ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-166054593]   = {["name"] = "Wild Turkey",               ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-229688157]   = {["name"] = "Water Snake",               ["givenItem"] ={ },      ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-229688157]   = {["name"] = "Water Snake",               ["givenItem"] ={ },      ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-1790499186]  = {["name"] = "Snake Red Boa",             ["givenItem"] ={ },      ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1464167925]   = {["name"] = "Snake Fer-De-Lance",        ["givenItem"] ={ },      ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [846659001]    = {["name"] = "Black-Tailed Rattlesnake",  ["givenItem"] ={ },      ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [545068538]    = {["name"] = "Western Rattlesnake",       ["givenItem"] ={ },      ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-1211566332]  = {["name"] = "Striped Skunk",             ["givenItem"] ={ },      ["money"] = 0.12,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [40345436]     = {["name"] = "Merino Sheep",              ["givenItem"] ={ },      ["money"] = 1.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 1729948479,   ["good"] = -1317365569,  ["perfect"] = 1466150167 },
    [-164963696]   = {["name"] = "Herring Seagull",           ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-1076508705]  = {["name"] = "Roseate Spoonbill",         ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [2023522846]   = {["name"] = "Dominique Rooster",         ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-466687768]   = {["name"] = "Red-Footed Booby",          ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-575340245]   = {["name"] = "Wester Raven",              ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1458540991]   = {["name"] = "North American Racoon",     ["givenItem"] ={},      ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-541762431]   = {["name"] = "Black-Tailed Jackrabbit",   ["givenItem"] ={},      ["money"] = 0.62,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1755643085]   = {["name"] = "American Pronghorn Doe",    ["givenItem"] ={ },      ["money"] = 1,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = -983605026,   ["good"] = 554578289,    ["perfect"] = -1544126829 },
    [2079703102]   = {["name"] = "Greater Prairie Chicken",   ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-1414989025]  = {["name"] = "Wirginia Possum",           ["givenItem"] ={ },      ["money"] = 0.05,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1007418994]   = {["name"] = "Berkshire Pig",             ["givenItem"] ={ },      ["money"] = 0.37,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = -308965548,   ["good"] = -57190831,    ["perfect"] = -1102272634 },
    [1416324601]   = {["name"] = "Ring-Necked Pheasant",      ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1265966684]   = {["name"] = "American White Pelican",    ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-1797450568]  = {["name"] = "Blue And Yellow Macaw",     ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1654513481]   = {["name"] = "Panther",                   ["givenItem"] ={ },      ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 1584468323,   ["good"] = -395646254,   ["perfect"] = 1969175294 },
    [1205982615]   = {["name"] = "Californian Condor",        ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-2063183075]  = {["name"] = "Dominique Chicken",         ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-2073130256]  = {["name"] = "Double-Crested Cormorant",  ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [90264823]     = {["name"] = "Cougar",                    ["givenItem"] ={ },      ["money"] = 1.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 1914602340,   ["good"] = 459744337,    ["perfect"] = -1791452194 },
    [-50684386]    = {["name"] = "Florida Cracker Cow",       ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 334093551,    ["good"] = 1150594075,   ["perfect"] = -845037222 },
    [480688259]    = {["name"] = "Coyote",                    ["givenItem"] ={ },      ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = -1558096473,  ["good"] = 1150939141,   ["perfect"] = -794277189 },
    [-564099192]   = {["name"] = "Whooping Crane",            ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },   
    [457416415]    = {["name"] = "Gila Monster",              ["givenItem"] ={ },      ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-753902995]   = {["name"] = "Alpine Goat",               ["givenItem"] ={ },      ["money"] = 0.12,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 699990316,    ["good"] = 1710714415,   ["perfect"] = -1648383828 },
    [723190474]    = {["name"] = "Canada Goose",              ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-2145890973]  = {["name"] = "Ferruinous Hawk",           ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1095117488]   = {["name"] = "Great Blue Heron",          ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-1854059305]  = {["name"] = "Green Iguana",              ["givenItem"] ={ },      ["money"] = 0.05,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-593056309]   = {["name"] = "Desert Iguana",             ["givenItem"] ={ },      ["money"] = 0.05,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1751700893]   = {["name"] = "Peccary Pig",               ["givenItem"] ={ },      ["money"] = 0.05,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = -99092070,    ["good"] = -1379330323,  ["perfect"] = 1963510418 },
    [386506078]    = {["name"] = "Common Loon",               ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-1098441944]  = {["name"] = "Moose",                     ["givenItem"] ={ },      ["money"] = 1.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 1868576868,   ["good"] = 1636891382,   ["perfect"] = -217731719 },
    [-1134449699]  = {["name"] = "American Muskrat",          ["givenItem"] ={ },      ["money"] = 0.1,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-861544272]   = {["name"] = "Great Horned Owl",          ["givenItem"] ={ },  ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [556355544]    = {["name"] = "Angus Ox",                  ["givenItem"] ={ },      ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 4623248928,   ["good"] = 1208128650,   ["perfect"] = 659601266 },
    [-1892280447]  = {["name"] = "Alligator",                 ["givenItem"] ={ },      ["money"] = 1,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 1806153689,   ["good"] = -802026654,   ["perfect"] = -1625078531 },
    [759906147]    = {["name"] = "North American Beaver",     ["givenItem"] ={ },      ["money"] = 0.37,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = -1569450319,  ["good"] = -2059726619,  ["perfect"] = 854596618 },
   -- [730092646]    = {["name"] = "American Black Bear",       ["givenItem"] ={ },      ["money"] = 1.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = 1083865179,   ["good"] = 1490032862,   ["perfect"] = 663376218 },
    [-1568716381]    = {["name"] = "Rocky Mountain Bighorn Sheep",       ["givenItem"] ={ },      ["money"] = 1.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,   ["good"] = nil,   ["perfect"] = nil },
    -- Fish
    [-711779521]   = {["name"] = "Longnose Gar",              ["givenItem"] ={ },      ["money"] = 1.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-1553593715]  = {["name"] = "Muskie",                    ["givenItem"] ={ },      ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-300867788]   = {["name"] = "Lake Sturgeon",             ["givenItem"] ={ },      ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1538187374]   = {["name"] = "Channel Catfish",           ["givenItem"] ={ },      ["money"] = 1,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [697075200]    = {["name"] = "Northern Pike",             ["givenItem"] ={ },      ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 3,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
}