Config = {}

Config.MinSwing = 1 -- Min Swings on a Rock
Config.MaxSwing = 3 -- Max Swings on a Rock

Config.Pickaxe = "pickaxe" -- Item from your database that you want to use for a pickaxe
Config.MinePromptKey = 0xD9D0E1C0 -- Key used to start Mining (Spacebar)
Config.StopMiningKey = 0x3B24C470 -- Key to stop Mining (F)
Config.MineRockKey = 0x07B8BEAF -- Key to Mine Rock (Left Click)

----- lower number is harder
Config.minDifficulty = 4000
Config.maxDifficulty = 2700
---------------------------
Config.Items = {
    {name = "clay", label = "Clay", chance = 6, amount = 4},
    {name = "coal", label = "Coal", chance = 8, amount = 4},
    {name = "copper", label = "Copper", chance = 5, amount = 2},
    {name = "iron", label = "Iron", chance = 6, amount = 2},
    {name = "nitrite", label = "Nitrite", chance = 8, amount = 2},
    {name = "rock", label = "Rocks", chance = 10, amount = 2},
    {name = "salt", label = "Salt", chance = 10, amount = 4},
    {name = "goldnugget", label = "Gold Nuggets", chance = 3, amount = 1},
}

Config.Rocks = {
    'bgv_rock_scree_sim_09',
    'old_hen_rock_scree_sim_08',
    's_gry_rock01x',
    'tal_rock_scree_sim_11',
    'dak_rock_scree_stg345_sim_02',
    'gri_rock_scree_sim_08',
    'hea_rock_scree_sim_10',
    'tal_rock_scree_sim_03',
    'cumb_rock_scree_sim_06',
    'old_hen_rock_scree_sim_11',
    'tal_rock_scree_sim_05',
    'hea_rock_scree_sim_09',
    'bgv_rock_scree_sim_11',
    'cumb_rock_scree_sim_11',
    'mp_roa_rock_grp_l_03',
    's_gri_rock_s_03',
    'sca_rock_scree_sim_04',
    'gri_rock_scree_sim_09',
    'sca_rock_scree_sim_01',
    'old_hen_rock_scree_sim_06',
    'gua_rock_scree_sim_03',
    'tal_rock_scree_sim_07',
    'bgv_rock_scree_sim_04',
    'sca_rock_scree_sim_09',
    'gri_rock_scree_sim_11',
    'bgv_rock_scree_sim_03',
    'dak_rock_scree_stg345_sim_03',
    'gri_rock_scree_sim_02',
    'gri_rock_scree_sim_02',
    'grp_rock_scree_sim_02',
    'grp_rock_scree_sim_10',
    'bgv_rock_scree_sim_06',
    'cumb_rock_scree_sim_10',
    'cumb_rock_scree_sim_04',
    'mp005_p_mp_rock_stash01',
    'sca_rock_scree_sim_08',
    'grp_rock_scree_sim_04',
    'grp_rock_scree_sim_06',
    'roa_rock_scree_sim_08',
    'hea_rock_scree_sim_05',
    'dak_rock_scree_stg345_sim_09',
    'bgv_rock_scree_sim_10',
    'old_hen_rock_scree_sim_04',
    'sca_rock_scree_sim_05',
    'hea_rock_scree_sim_03',
    'tal_rock_scree_sim_01',
    'old_hen_rock_scree_sim_05',
    'vfx_scree_rock_01',
    'tal_rock_scree_sim_06',
    'roa_rock_scree_sim_11',
    'tal_rock_scree_sim_08',
    'bgv_rock_scree_sim_01',
    'sca_rock_scree_sim_03',
    'sca_rock_scree_sim_10',
    'p_int_rockhang03x',
    'old_hen_rock_scree_sim_01',
    'roa_rock_scree_sim_09',
    'hea_rock_scree_sim_11',
    'hea_rock_scree_sim_02',
    'hea_rock_scree_sim_07',
    'grp_rock_scree_sim_09',
    'gua_rock_scree_sim_06',
    'old_hen_rock_scree_sim_10',
    'tal_rock_scree_sim_02',
    's_gri_rock_l_03',
    's_gri_rock_m_03',
    'mp_big_rock_scan_07',
    'cumb_rock_scree_sim_077',
    'roa_rock_scree_sim_01',
    'mp_p_rock_mssgry_lrg_b',
    'mp_sca_rock_grp_l_02',
    'bgv_rock_scree_sim_08',
    'alp_rock_scree_sim_08',
    'grp_rock_scree_sim_01',
    'alp_rock_scree_sim_04',
    'hea_rock_scree_sim_08',
    'tal_rock_scree_sim_04',
    'alp_rock_scree_sim_07',
    'gua_rock_scree_sim_01',
    'bgv_rock_scree_sim_02',
    'dak_rock_scree_stg345_sim_01',
    'p_rock_stash01',
    'gri_rock_scree_sim_01',
    'dak_rock_scree_stg345_sim_04',
    'roa_rock_scree_sim_06',
    'old_hen_rock_scree_sim_09',
    'gua_rock_scree_sim_02',
    'dak_rock_scree_stg345_sim_08',
    'alp_rock_scree_sim_02',
    'cumb_rock_scree_sim_03',
    'roa_rock_scree_sim_07',
    'cumb_rock_scree_sim_02',
    'old_hen_rock_scree_sim_02',
    'alp_rock_scree_sim_01',
    'bgv_rock_scree_sim_05',
    'cumb_rock_scree_sim_09',
    'roa_rock_scree_sim_04',
    'sca_rock_scree_sim_07',
    'gri_rock_scree_sim_04',
    'cumb_rock_scree_sim_08',
    'tal_rock_scree_sim_09',
    'alp_rock_scree_sim_03',
    'alp_rock_scree_sim_09',
    'alp_rock_scree_sim_10',
    'sca_rock_scree_sim_11',
    'hea_rock_scree_sim_04'
}