Config2 = {}
Config2.Language = {
    ["presstobuy"] = "Waffen anpassen",
    ["presstocraft"] = "Waffen herstellen",
    ["presstoshop"] = "Waffenladen",
    ["tooclose"] = "Jemand ist zu nah",
    ["openmenu"] = "Öffnen",
    ["rotateitem1"] = "Drücke ~e~1~q~ zum Waffe drehen",
    ["rotateitem2"] = "Drücke ~e~2~q~ zum Waffe drehen",
    ["rotateitem3"] = "Drücke ~e~3~q~ zum Waffe drehen",
    ["rotateitem4"] = "Drücke ~e~4~q~ zum Waffe drehen",

    ["dollar"] = " $",



    ["craftingloading"] = "Herstellen...",
    ["customloading"] = "Anpassungen montieren..",
    ["pleaserequip"] = "Bitte rüste deine Waffe aus dem Inventar aus",
    ["scrolltoexit"] = "Scrolle nach unten, um das Menü zu verlassen",
    ["wrongjobcuztom"] = "Du hast nicht den erforderlichen Job/Rang, um die Anpassungen vorzunehmen",
    ["wrongjobcrafting"] = "Du hast nicht den erforderlichen Job/Rang, um Waffen herzustellen",
    ["customization"] = "Waffen anpassen",
    ["crafting"] = "Herstellung",
    ["shop"] = "Waffenladen",
    ["buyweapons"] = "Kaufe Waffen",
    ["buyammo"] = "Kaufe Munition",
    ["weaponcrafting"] = "Waffenherstellung",
    ["ammocrafting"] = "Munitionsherstellung",
    ["areusureexit"] = "Bist du sicher, dass du fertig bist ?",
    ["comps"] = "Weapon Components",
    ["sights"] = "Weapon Sights",
    ["rifling"] = "Weapon Rifling",
    ["other"] = "Weapon Barrel",
    ["scopecolor"] = "Scope Material",
    ["wrap"] = "Weapon Wrap",
    ["wrapcolor"] = "Wrap Color",
    ["barrel"] = "Barrel Material",
    ["trigger"] = "Trigger Material",
    ["variant"] = "Weapon Variant",
    ["frame"] = "Frame Material",
    ["frontsight"] = "Frontsight Material",
    ["cylinder"] = "Mechanism Material",
    ["gripbody"] = "Grip Material",
    ["grip"] = "Grip Decal",
    ["decal"] = "Weapon Decals",
    ["decalcylinder"] = "Mechanism Decals",
    ["decalframe"] = "Frame Decals",
    ["decalbarrel"] = "Barrel Decals",
    ["decalcolor"] = "Decals Material",
    ["cylinder2"] = "Mechanism Decals Material",
    ["frame2"] = "Frame Decals Material",
    ["barrel2"] = "Barrel Decals Material",
    ["buyselect"] = "Auswahl kaufen",
    ["total"] = "Total: ",
    ["exitmenu"] = "Menü verlassen",
    ["cost"] = "Kostet: ",
    ["craft"] = "Herstellen",
    ["count"] = "Anzahl: ",
    ["yes"] = "Ja",
    ["no"] = "Nein",
    ["remove"] = "Entfernen",
    ["price"] = " / Preis: ",
    ["label"] = "Etikette: ",
    ["wrongwptype"] = "Falscher Waffentyp",
    ["craftingwepmods"] = "Waffen Mods herstellen",
    ["cantafford"] = "Kann ich mir nicht leisten",
    ["syn_weapons"] = "Waffen: ",
    ["bought"] = " Gekauft ",
    ["youboughta"] = "Du kaufst ein ",
    ["fors"] = " für ",
    ["nomoney"] = "Du hast nicht genug Geld",
    ["cantcarrywep"] = "Du kannst nicht mehr Waffen tragen",
    ["cantcarryitem"] = "Du kannst nicht mehr tragen",
    ["crafted"] = " Hergestellt ",
    ["nomaterial"] = "Nicht genug Materialien",
    ["weprec"] = "Du hast eine Waffe erhalten",




    ----- new lines
    ["confirm"] = "Bestätigen",
    ["amount"] = "Menge",
    ["invalidamount"] = "Ungültige Menge",
}
