Config2 = {}
Config2.Language = {
    ["presstobuy"] = "Customize Weapons",
    ["presstocraft"] = " Craft Weapons",
    ["presstoshop"] = "Gunsmith Shop",
    ["tooclose"] = "Someone is too close",
    ["openmenu"] = "Open",
    ["rotateitem1"] = "Press ~e~1~q~ To Rotate Weapon",
    ["rotateitem2"] = "Press ~e~2~q~ To Rotate Weapon",
    ["rotateitem3"] = "Press ~e~3~q~ To Rotate Weapon",
    ["rotateitem4"] = "Press ~e~4~q~ To Rotate Weapon",

    ["dollar"] = " $",



    ["craftingloading"] = "Crafting...",
    ["customloading"] = "Crafting Cuztomizations..",
    ["pleaserequip"] = "lease requip your weapon from inventory",
    ["scrolltoexit"] = "Scroll To The Bottom To Exit Menu",
    ["wrongjobcuztom"] = "You Do not have the required job/rank to use cuztomization",
    ["wrongjobcrafting"] = "You Do not have the required job/rank to use crafting",
    ["customization"] = "Weapon Customization",
    ["crafting"] = "Crafting",
    ["shop"] = "Weapons Shop",
    ["buyweapons"] = "Buy Weapons",
    ["buyammo"] = "Buy Ammo",
    ["weaponcrafting"] = "Weapon Crafting",
    ["ammocrafting"] = "Ammo Crafting",
    ["areusureexit"] = "Are You Sure You Want To Exit ?",
    ["comps"] = "Weapon Components",
    ["sights"] = "Weapon Sights",
    ["rifling"] = "Weapon Rifling",
    ["other"] = "Weapon Barrel",
    ["scopecolor"] = "Scope Material",
    ["wrap"] = "Weapon Wrap",
    ["wrapcolor"] = "Wrap Color",
    ["barrel"] = "Barrel Material",
    ["trigger"] = "Trigger Material",
    ["variant"] = "Weapon Variant",
    ["frame"] = "Frame Material",
    ["frontsight"] = "Frontsight Material",
    ["cylinder"] = "Mechanism Material",
    ["gripbody"] = "Grip Material",
    ["grip"] = "Grip Decal",
    ["decal"] = "Weapon Decals",
    ["decalcylinder"] = "Mechanism Decals",
    ["decalframe"] = "Frame Decals",
    ["decalbarrel"] = "Barrel Decals",
    ["decalcolor"] = "Decals Material",
    ["cylinder2"] = "Mechanism Decals Material",
    ["frame2"] = "Frame Decals Material",
    ["barrel2"] = "Barrel Decals Material",
    ["buyselect"] = "Buy Selection",
    ["total"] = "Total: ",
    ["exitmenu"] = "Exit Menu",
    ["cost"] = "Cost: ",
    ["craft"] = "Craft",
    ["count"] = "Count: ",
    ["yes"] = "Yes",
    ["no"] = "No",
    ["remove"] = "Remove",
    ["price"] = " / Price: ",
    ["label"] = "Label: ",
    ["wrongwptype"] = "Wrong Weapon Type",
    ["craftingwepmods"] = "Crafting Weapon Mods",
    ["cantafford"] = "Cant Afford",
    ["syn_weapons"] = "Weapons: ",
    ["bought"] = " Bought ",
    ["youboughta"] = "You Bought A ",
    ["fors"] = " For ",
    ["nomoney"] = "You Dont have Enough Money",
    ["cantcarrywep"] = "Cant Carry More Weapons",
    ["cantcarryitem"] = "Cant Carry More items",
    ["crafted"] = " Crafted ",
    ["nomaterial"] = "Not Enough Materials",
    ["weprec"] = "You Recieved a Weapon",




    ----- new lines
    ["confirm"] = "Confirm",
    ["amount"] = "Amount",
    ["invalidamount"] = "Invalid Amount",
}
